package com.myspace.employeerating;


/**
 * This class was automatically generated by the data modeler tool.
 */

public class Employee implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Employee() {
        System.err.println("Employee Object");
    }
    
    private Integer empId;
    
    private String name;
    
    private Integer yearsOfExperience;
    
    private String rating;
    
    private Double amountOfHike;


    	public Integer getEmpId() {
		return empId;
	}

	public void setEmpId(Integer empId) {
		this.empId = empId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getYearsOfExperience() {
		return yearsOfExperience;
	}

	public void setYearsOfExperience(Integer yearsOfExperience) {
		this.yearsOfExperience = yearsOfExperience;
	}

	public String getRating() {
		return rating;
	}

	public void setRating(String rating) {
		this.rating = rating;
	}

	public Double getAmountOfHike() {
		return amountOfHike;
	}

	public void setAmountOfHike(Double amountOfHike) {
		this.amountOfHike = amountOfHike;
	}



}